server:
  port: 8000
spring:
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb+srv://amrita:amrita123456@cluster0.gzcih.mongodb.net/accounting
      database: accounting


